### ISSUE TITLE
new version of seqdiag breaks builds

### ISSUE THREAD

**Issue by ni-rnias** [blockdiag/sphinxcontrib-seqdiag#7]
Hiya,

Two days ago (Jan 26th 2020), version `2.0.0` of `seqdiag` and `blockdiag` were released. this caused our doc builds to fail:

```
making output directory...
Original exception:
Traceback (most recent call last):
File "/path/to/project/env/lib/python3.6/site-packages/sphinx/application.py", line 474, in setup_extension
mod = __import__(extension, None, None, ['setup'])
File "/path/to/project/env/lib/python3.6/site-packages/sphinxcontrib/seqdiag.py", line 28, in <module>
from blockdiag.utils.compat import u, string_types
ImportError: cannot import name 'u'
```

Workaround: pin `seqdiag==0.9.6` and `blockdiag==1.5.4` in project requirements.

I propose that this library's requirements are changed to include `seqdiag>=0.9.3,<2` and `blockdiag>=1.5.0,<2`.

**Comment by tk0miya** [comment]
Oh... I should upgrade sphinxcontrib-*diag also. Please wait a moment. I'll work in tonight (in JST).

**Comment by tk0miya** [comment]
What version of sphinxcontrib-seqdiag have you use? It seems sphinxcontrib-seqdiag-2.0.0 works fine with blockdiag-2.0.

**Comment by ni-rnias** [comment]
Ah yes, I'm using `sphinxcontrib-seqdiag==0.8.5`. I did not see that there was a new version available. My mistake, sorry!
